title: Elizabeth Earl # your name (or website title) here
logo: "/images/picture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https:/esanch.github.io">My Portfolio</a>
  <br>
  <a href="https://esanch.github.io/README">Project's descriptions</a>
  <br>
  <a href="https://esanch.github.io/about_me">About Me</a>
  
 
theme: jekyll-theme-minimal
