title: Elizabeth Earl # your name (or website title) here
logo: "/images/picture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https:/esanch.github.io">My Portfolio</a>
  <br>
  <a href="https://esanch.github.io/about_me">About Me</a>
  <br>
  <a href="https://esanch.github.io/contact_me">Contact Me</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
